# Generated by Django 3.0.6 on 2020-05-05 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
